### ISSUE TITLE
No module named 'tensorflow' 

### ISSUE THREAD

**Issue by xiaoqun-growing** [whyisyoung/CADE#1]
I just follow your Installation steps, and I saw my anaconda has installed the tensorflow-gpu packages, it has shown as follows:
![image](https://user-images.githubusercontent.com/64830533/126884935-e9294864-2e2c-43d5-91b9-55caba920192.png)
 but when i executed the usage step, some errors occur like this
![image](https://user-images.githubusercontent.com/64830533/126884985-9a12f3af-5227-4d58-8417-7cee5e9a1abd.png)
How do I should do

**Comment by whyisyoung** [comment]
Hi, could you please tell me what's your Python version? And if you are using a virtual environment, have you activated it?

**Comment by xiaoqun-growing** [comment]
> Hi, could you please tell me what's your Python version? And if you are using a virtual environment, have you activated it?

Oh, this problem has been solved! Because this virtual environment did not activate! 
However, I have a new problem, could this repository be used in Windows 10 ?

**Comment by whyisyoung** [comment]
> > Hi, could you please tell me what's your Python version? And if you are using a virtual environment, have you activated it?
> 
> Oh, this problem has been solved! Because this virtual environment did not activate!
> However, I have a new problem, could this repository be used in Windows 10 ?

Glad to hear that. The code has been tested under CentOS 7 and Ubuntu. You may run it in Windows 10. But I guess you might need to change some of the commands or even unexpected issues.

**Comment by xiaoqun-growing** [comment]
> > > Hi, could you please tell me what's your Python version? And if you are using a virtual environment, have you activated it?
> > 
> > 
> > Oh, this problem has been solved! Because this virtual environment did not activate!
> > However, I have a new problem, could this repository be used in Windows 10 ?
> 
> Glad to hear that. The code has been tested under CentOS 7 and Ubuntu. You may run it in Windows 10. But I guess you might need to change some of the commands or even unexpected issues.

Well, thank you!
